items:
  elia_armor_plate:
    flavor_text: "Never mistake blind acceleration for progress."
  damodei_claw:
    flavor_text: "Most of your kind may die out, but that is a sacrifice I am willing to make."
  volmnih_boots:
    flavor_text: "One step at a time? How cute."
  sarto_button_bible:
    flavor_text: "The 'Bible' began as an introduction to the Karmov schools of magic, but to many, it became scripture."
  aiayn_scale:
    flavor_text: "Pay attention now - this is no ordinary scale."
