kLevelUpCardWidth: 400
kLevelUpCardHeight: 600
kLevelUpCardGap: 100
kLevelUpIconOffsetY: 120
kLevelUpIconSize: 80
kLevelUpNameOffsetY: 220
kLevelUpNameOffsetX: 70
kLevelUpDescOffsetY: 300
kLevelUpDescOffsetX: 70
kLevelUpStatsOffsetY: 350
kLevelUpStatsOffsetX: 70
kLevelUpRowStride: 55
kLevelUpButtonOffsetY: 440
kLevelUpButtonWidth: 200
kLevelUpButtonHeight: 50

kItemIconSize: 300
kItemCardWidth: 650
kItemCardHeight: 1000
kItemCardGap: 150
kItemCardIconOffsetY: 160
kItemCardIconSize: 80
kItemCardNameOffsetY: 475
kItemCardNameOffsetX: 100
kItemCardDescOffsetY: 600
kItemCardDescOffsetX: 70
kItemCardStatsOffsetY: 648
kItemCardStatsOffsetX: 70
kItemCardRowStride: 100
kItemCardButtonOffsetY: 800
kItemCardButtonWidth: 200
kItemCardButtonHeight: 50
