level_up_card_width: 400
level_up_card_height: 600
level_up_card_gap: 100
level_up_icon_offset_y: 120
level_up_icon_size: 80
level_up_name_offset_y: 220
level_up_name_offset_x: 70
level_up_desc_offset_y: 300
level_up_desc_offset_x: 70
level_up_stats_offset_y: 350
level_up_stats_offset_x: 70
level_up_row_stride: 55
level_up_button_offset_y: 440
level_up_button_width: 200
level_up_button_height: 50

item_icon_size: 300
item_card_width: 650
item_card_height: 1000
item_card_gap: 150
item_card_icon_offset_y: 160
item_card_icon_size: 80
item_card_name_offset_y: 475
item_card_name_offset_x: 100
item_card_desc_offset_y: 600
item_card_desc_offset_x: 70
item_card_stats_offset_y: 648
item_card_stats_offset_x: 70
item_card_row_stride: 100
item_card_button_offset_y: 800
item_card_button_width: 200
item_card_button_height: 50
