level_up_card_width: 500
level_up_card_height: 950
level_up_card_gap: 100
level_up_icon_offset_y: 145
level_up_icon_size: 80
level_up_name_offset_y: 250
level_up_name_offset_x: 70
level_up_name_label_height: 5
level_up_desc_offset_y: 320
level_up_desc_offset_x: 70
level_up_desc_label_height: 5
level_up_stats_offset_y: 370
level_up_stats_label_height: 5
level_up_stats_offset_x: 70
level_up_row_stride: 105
level_up_button_offset_y: 765
level_up_button_width: 200
level_up_button_height: 50

item_icon_size: 200
item_card_width: 650
item_card_height: 1000
item_card_gap: 150
item_card_icon_offset_y: 180
item_card_name_offset_y: 400
item_card_name_offset_x: 100
item_card_flavor_text_offset_y: 525
item_card_flavor_text_offset_x: 100
item_card_desc_offset_y: 600
item_card_desc_offset_x: 70
item_card_stats_offset_y: 648
item_card_stats_offset_x: 70
item_card_row_stride: 100
item_card_button_offset_y: 800
item_card_button_width: 200
item_card_button_height: 50
